export const ACTIONS = {
  BUY_CAKE: 'BUY_CAKE',
  BUY_ICECREAM: 'BUY_ICECREAM',
  BUY_COOKIE: 'BUY_COOKIE',
  FETCH_REQUEST: 'FETCH_REQUEST',
  FETCH_SUCCESS: 'FETCH_SUCCESS',
  FETCH_FAILED: 'FETCH_FAILED',
};